# hash:sha256:fd4f924fc956ba2803b9b949f2c5f93f8e3964fd76b5e4dffa65a69114846d83
ARG REGISTRY_HOST
FROM $REGISTRY_HOST/codeocean/mosuite-minimal:v0.5.0

ARG DEBIAN_FRONTEND=noninteractive
ARG GIT_ASKPASS
COPY git-ask-pass /
